#!/bin/bash
# Prepare a PATCH file to be applied by apply_patch
# Needs wget, patch, unzip
REV=$(cat SVN_REVISION)
if [ ! -d wp34s-code-$REV-trunk ]
then
    svn checkout -$REV svn://svn.code.sf.net/p/wp34s/code/trunk/ wp34s-code-$REV-trunk
fi
cd wp34s-code-$REV-trunk
patch < ../makefile.diff
patch < ../xeq.diff
make
cp -r Linux64/consts/ consts
cd ..

mkdir decNumber
mkdir consts
ln -s ../decNumber consts

for file in $(cat SVN_MANIFEST)
do
    cp wp34s-code-$REV-trunk/$file $file
done
patch -p1 < PATCH
