--- Makefile.old	2021-02-19 07:51:43.223091608 +0100
+++ Makefile	2021-02-19 07:51:53.051117868 +0100
@@ -34,7 +34,7 @@
 #INFRARED = 1
 endif
 
-BASE_CFLAGS := -Wall -Werror -g -fno-common -fno-exceptions 
+BASE_CFLAGS := -Wall -g -fno-common -fno-exceptions 
 OPT_CFLAGS := -Os -fira-region=one
 USE_CURSES := -DUSECURSES=1
 
